# Generated by Django 3.1.4 on 2020-12-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
    ]
